### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by websashka** [ton-utils/reverse-proxy#1]
panic: assignment to entry in nil map

goroutine 142 [running]:
github.com/xssnick/tonutils-go/adnl/dht.(*Client).nodeStateHandler.func1(0xc000246fc0, 0xc0e747de445b95d8?)
	/Users/alexander/go/pkg/mod/github.com/xssnick/tonutils-go@v1.4.1-0.20230106083652-c58b9000f753/adnl/dht/client.go:172 +0x7d
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).changeState(0xc000246fc0, 0x2)

**Comment by websashka** [comment]
bind: can't assign requested address - when I switched on upd-rldp-2 branch of tonutils-go repository.

**Comment by xssnick** [comment]
Thank you, should be fixed already
